# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.5"
manifest_format = "2.0"
project_hash = "eadaeec0a079989586fcec4e0813620d4bed28f9"

[[deps.Skipper]]
git-tree-sha1 = "725fc552fd61f56990db3ab30903b94fd16d9182"
uuid = "fc65d762-6112-4b1c-b428-ad0792653d81"
version = "0.1.15"

    [deps.Skipper.extensions]
    AccessorsExt = "Accessors"
    AxisKeysExt = "AxisKeys"
    DictionariesExt = "Dictionaries"
    MakieExt = "Makie"

    [deps.Skipper.weakdeps]
    Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
    AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
    Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
    Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
